### ISSUE TITLE
Gzip-compressed data is corrupt

### ISSUE THREAD

**Issue by vzinche** [mobie/platybrowser-project#85]
Taking a BDV screenshot of a normal looking area I get a missing block and an error 'Error loading setup0/timepoint0/s0 at block [207, 212, 10]: java.io.IOException: Gzip-compressed data is corrupt'

![epi3](https://user-images.githubusercontent.com/32451366/123225083-a87e4400-d4d2-11eb-9c02-4fee3f0cd34d.jpg)

The position is 
{"normalizedAffine":[0.026346829603594083,0.0,0.0,-5.155998001838155,0.0,0.026346829603594083,0.0,-5.277718271115512,0.0,0.0,0.026346829603594083,-2.884630281549574],"timepoint":0}

**Comment by constantinpape** [comment]
Thanks for reporting, I will try to fix this at some point.

**Comment by vzinche** [comment]
Just in case, I've seen it in multiple areas of the animal

**Comment by constantinpape** [comment]
Yes, I know. This is due to some data corruption that happened on EMBL S3 a while ago. I have a script that fixes it and that worked for all other datasets, but it did not run through completely for platy due to some timeout ...

**Comment by constantinpape** [comment]
This is fixed now.
