### ISSUE TITLE
clean up python scripts

### ISSUE THREAD

**Issue by tischi** [mobie/platybrowser-project#96]
@constantinpape 

There are a bunch of python scripts in the project root folder and also in `misc`; would it be OK if I also move the python scripts in the main folder into `misc`?

**Comment by constantinpape** [comment]
Yes, the scripts are outdated and can be moved to `misc`. They wouldn't work anymore because they are made for the old project layout, before we had the full MoBIE layout defined.

**Comment by tischi** [comment]
Does that mean that I also should move the [whole mmpb folder](https://github.com/mobie/platybrowser-project/tree/main/mmpb) to `misc/outdated` ?

**Comment by constantinpape** [comment]
> Does that mean that I also should move the [whole mmpb folder](https://github.com/mobie/platybrowser-project/tree/main/mmpb) to `misc/outdated` ?

I would no do that for now. This contains also logic for running the segmentation and computing features that should still work fine.

**Comment by tischi** [comment]
Done [f30bceb](https://github.com/mobie/platybrowser-project/commit/f30bceb22d619ec61c20aeff89d843c298a4aeec)
